# VPN IP
db_host_ip: 'gAAAAABgMsR7b8mp5aeMPB0JSuRb2tppsK8fB2Xe1yM5rexQrhI6--3IfJVoW_Soh56rwo_h2Hbjz-NuEgsOmB7-rQQko0ijtA=='

# UAT Internal IP
# db_host_ip : 'gAAAAABgUR9aA_wwr7rFgZ3p0wBmKtZb9W-KeKz5tl8McGsaARUGWmf3JPpGP43yCltMGRpau2bd5PwKYK0yB3F0Nwt3KiN0Fg=='

db_port: 'gAAAAABgMsSdWWwwuqHBX-OvIR5Auqh8TN8nYVqZYVmXSxn-Tzj0vCyEqo6ohcpoJnbEQSMJI-6XW7ele7nDYpxhtHFx-temeA=='

# UAT new db
db_tag: 'gAAAAABgfUZOvjcznE614VQggRicaTWUdWVwASQfG1E3NMTJ8GlpUlSUZeyRAQ-ShWBRsupFhCxuQdJtVv5g2RRMXdh_yULN5g=='
db_user: 'gAAAAABgfUYQumtvi9cP_zzLWWX9TeIVw1lxmCshSpQbiAu_V471Bj7G6Bn-8JRpuxxuKvRXArzOfrD9KGoi0X0hz6tZqzp7iQ=='
db_pwd: 'gAAAAABgfUZ1Y5a8Ye4921UHP6LXwGJxidD1oA0obCchKYxueJ5ZKELZv_s37PCEsHOEDTNDCgToXdCGswf08L2s5If9QUVM_Q=='

onboarding_queue: 'ml-facerecognition-onboard-request'
retraining_queue: 'ml-facerecognition-retrain-model'

redis_host: '10.72.15.119'
redis_port: 6379

model_users_threshold: 10
flag_store_recognition_images: 1
